Repository Beat-to-the-Book/BE, pull requests merged in 2025-05, with the labels that each got.

#25 Fix: 사용자의 대여/구매 기록 조회 API
  src/main/java/org/be/book/controller/PurchaseController.java
  src/main/java/org/be/book/controller/RentalController.java
  src/main/java/org/be/book/dto/HistoryPurchaseResponse.java
  src/main/java/org/be/book/service/PurchaseService.java
  src/main/java/org/be/book/service/RentalService.java
Labels: fix

#26 refc : FE 요구사항 맞춰서 수정함(4가지)
  src/main/java/org/be/auth/config/JwtAuthenticationFilter.java
  src/main/java/org/be/auth/config/SecurityConfig.java
  src/main/java/org/be/auth/controller/AuthController.java
  src/main/java/org/be/auth/dto/UserInfoResponse.java
  src/main/java/org/be/community/controller/CommunityPostController.java
  src/main/java/org/be/community/repository/CommunityPostRepository.java
  src/main/java/org/be/community/service/CommunityPostService.java
  src/main/java/org/be/group/controller/GroupMemberController.java
  src/main/java/org/be/group/dto/GroupRoleResponseDto.java
Labels: refactor

#27 refc : 중복된 /my api 삭제
  src/main/java/org/be/group/controller/GroupMemberController.java
Labels: feature

#32 fix : 다른 도메인 요청 허용하도록 수정
  src/main/java/org/be/auth/controller/AuthController.java
Labels: fix

#34 Fix: 첫 번째 추천 요청 시 추천 결과가 전달되지 않던 문제 해결
  src/main/java/org/be/recommend/controller/RecommendController.java
  src/main/java/org/be/recommend/dto/RecommendResponse.java
Labels: fix

#35 fix : auth 부분 authorization header 형식으로 다시 변경
  src/main/java/org/be/auth/config/CorsConfig.java
  src/main/java/org/be/auth/config/JwtAuthenticationFilter.java
  src/main/java/org/be/auth/controller/AuthController.java
  src/main/java/org/be/auth/dto/TokenResponse.java
  src/main/java/org/be/auth/service/AuthService.java
Labels: fix

#36 fix : communiy 부분 authorization header 형식으로 다시 변경
  src/main/java/org/be/community/controller/CommunityPostController.java
Labels: fix

#37 fix : group 부분 authorization header 형식으로 다시 변경
  src/main/java/org/be/group/controller/GroupController.java
  src/main/java/org/be/group/controller/GroupMemberController.java
  src/main/java/org/be/group/controller/MyGroupController.java
Labels: fix
