Repository Beat-to-the-Book/BE, pull requests merged in 2025-03, with the labels that each got.

#1 Docker 세팅 및 의존성 추가
  Dockerfile
  build.gradle
  compose.yaml
  src/main/resources/application.properties
Labels: feature

#3 [chore] gitignore, build.gradle 추가
  .gitignore
  build.gradle
Labels: chore

#4 [feature] auth(로그인, 회원가입, validate) 기능 구현
  src/main/java/org/be/auth/config/CorsConfig.java
  src/main/java/org/be/auth/config/JwtAuthenticationFilter.java
  src/main/java/org/be/auth/config/JwtTokenProvider.java
  src/main/java/org/be/auth/config/SecurityConfig.java
  src/main/java/org/be/auth/controller/AuthController.java
  src/main/java/org/be/auth/dto/ApiResponse.java
  src/main/java/org/be/auth/dto/LoginRequest.java
  src/main/java/org/be/auth/dto/RegisterRequest.java
  src/main/java/org/be/auth/dto/TokenResponse.java
  src/main/java/org/be/auth/exception/AuthExceptionHandler.java
  src/main/java/org/be/auth/exception/CustomException.java
  src/main/java/org/be/auth/model/User.java
  src/main/java/org/be/auth/repository/UserRepository.java
  src/main/java/org/be/auth/service/AuthService.java
  src/main/java/org/be/auth/service/CustomUserDetails.java
  src/main/java/org/be/auth/service/CustomUserDetailsService.java
Labels: feature

#5 [feature] api json 응답 반환하도록 추가
  src/main/java/org/be/auth/controller/AuthController.java
  src/main/java/org/be/auth/dto/ApiResponse.java
Labels: feature

#7 [feature] Book 기본 기능 구현
  src/main/java/org/be/book/controller/BookController.java
  src/main/java/org/be/book/controller/PurchaseController.java
  src/main/java/org/be/book/controller/RentalController.java
  src/main/java/org/be/book/dto/CreateBookRequest.java
  src/main/java/org/be/book/model/Book.java
  src/main/java/org/be/book/model/Purchase.java
  src/main/java/org/be/book/model/Rating.java
  src/main/java/org/be/book/model/Rental.java
  src/main/java/org/be/book/repository/BookRepository.java
  src/main/java/org/be/book/repository/PurchaseRepository.java
  src/main/java/org/be/book/repository/RentalRepository.java
  src/main/java/org/be/book/service/BookService.java
  src/main/java/org/be/book/service/PurchaseService.java
  src/main/java/org/be/book/service/RentalService.java
Labels: feature

#6 [fix] 인증된 사용자 정보를 SecurityContext에 등록하도록 JwtAuthenticationFilter 수정
  src/main/java/org/be/auth/config/JwtAuthenticationFilter.java
Labels: fix

#9 [Feature] Kafka, Redis 기반 도서 추천 기능 구현
  src/main/java/org/be/recommend/config/RedisConfig.java
  src/main/java/org/be/recommend/controller/RecommendController.java
  src/main/java/org/be/recommend/service/KafkaConsumerService.java
  src/main/java/org/be/recommend/service/KafkaProducerService.java
  src/main/java/org/be/recommend/service/RecommendService.java
  src/main/java/org/be/recommend/service/RedisService.java
Labels: feature

#11 크롤링 1차 커밋(미완)
  build.gradle
  src/main/java/org/be/BeApplication.java
  src/main/java/org/be/auth/config/SecurityConfig.java
  src/main/java/org/be/book/controller/BookController.java
  src/main/java/org/be/book/dto/AddBookRequest.java
  src/main/java/org/be/book/model/Book.java
  src/main/java/org/be/book/repository/BookRepository.java
  src/main/java/org/be/book/service/BookCrawlingService.java
  src/main/java/org/be/book/service/BookService.java
Labels: feature

#12 Feature: Redis, Kafka 로직 대폭 추가
  src/main/java/org/be/book/controller/PurchaseController.java
  src/main/java/org/be/book/dto/HistoryPurchaseResponse.java
  src/main/java/org/be/book/model/Purchase.java
  src/main/java/org/be/book/repository/PurchaseRepository.java
  src/main/java/org/be/book/repository/RentalRepository.java
  src/main/java/org/be/book/service/PurchaseService.java
  src/main/java/org/be/recommend/config/RedisConfig.java
  src/main/java/org/be/recommend/controller/RecommendController.java
  src/main/java/org/be/recommend/dto/BookDto.java
  src/main/java/org/be/recommend/dto/BookMessage.java
  src/main/java/org/be/recommend/dto/RecommendationMessage.java
  src/main/java/org/be/recommend/service/KafkaConsumerService.java
  src/main/java/org/be/recommend/service/KafkaProducerService.java
  src/main/java/org/be/recommend/service/RecommendService.java
  src/main/java/org/be/recommend/service/RedisService.java
Labels: feature
