Repository Beat-to-the-Book/BE, pull requests merged in 2025-04, with the labels that each got.

#15 feat: 구체 장르 추출, 없는 책 커버 흰색 대체
  Dockerfile
  Dockerfile.spring
  src/main/java/org/be/auth/config/SecurityConfig.java
  src/main/java/org/be/book/model/Book.java
  src/main/java/org/be/book/service/BookCrawlingService.java
  src/main/resources/static/images/default_cover.jpg
Labels: feature

#16 fix: 여러 페이지 크롤링 되도록 수정 + 19세 이상 도서 제외
  src/main/java/org/be/book/service/BookCrawlingService.java
Labels: fix

#17 feat : 책 개별 조회 메서드 추가
  src/main/java/org/be/book/controller/BookController.java
  src/main/java/org/be/book/service/BookService.java
Labels: feature

#18 Feature/community
  src/main/java/org/be/BeApplication.java
  src/main/java/org/be/auth/config/JwtAuthenticationFilter.java
  src/main/java/org/be/auth/config/SecurityConfig.java
  src/main/java/org/be/auth/model/User.java
  src/main/java/org/be/auth/service/CustomUserDetails.java
  src/main/java/org/be/auth/service/CustomUserDetailsService.java
  src/main/java/org/be/community/controller/CommunityPostController.java
  src/main/java/org/be/community/dto/CommunityPostRequestDto.java
  src/main/java/org/be/community/dto/CommunityPostResponseDto.java
  src/main/java/org/be/community/entity/CommunityPost.java
  src/main/java/org/be/community/repository/CommunityPostRepository.java
  src/main/java/org/be/community/service/CommunityPostService.java
Labels: feature

#19 Fix: 사용자 행동 데이터 기반으로 추천 요청하도록 수정
  build.gradle
  src/main/java/org/be/auth/config/SecurityConfig.java
  src/main/java/org/be/book/controller/BookController.java
  src/main/java/org/be/book/dto/AddBookRequest.java
  src/main/java/org/be/book/model/Purchase.java
  src/main/java/org/be/recommend/controller/RecommendController.java
  src/main/java/org/be/recommend/dto/BehaviorRequest.java
  src/main/java/org/be/recommend/dto/BookMessage.java
  src/main/java/org/be/recommend/dto/FlaskRecommendationMessage.java
  src/main/java/org/be/recommend/dto/RecommendationResultMessage.java
  src/main/java/org/be/recommend/service/KafkaConsumerService.java
  src/main/java/org/be/recommend/service/KafkaProducerService.java
  src/main/java/org/be/recommend/service/RecommendService.java
Labels: fix

#20 feat : group 기능 api 8개 구현
  src/main/java/org/be/community/entity/CommunityPost.java
  src/main/java/org/be/group/controller/GroupController.java
  src/main/java/org/be/group/controller/GroupMemberController.java
  src/main/java/org/be/group/controller/MyGroupController.java
  src/main/java/org/be/group/dto/GroupCreateRequestDto.java
  src/main/java/org/be/group/dto/GroupJoinRequestDto.java
  src/main/java/org/be/group/dto/GroupMemberResponseDto.java
  src/main/java/org/be/group/dto/GroupResponseDto.java
  src/main/java/org/be/group/entity/GroupMember.java
  src/main/java/org/be/group/entity/UserGroup.java
  src/main/java/org/be/group/repository/GroupMemberRepository.java
  src/main/java/org/be/group/repository/GroupRepository.java
  src/main/java/org/be/group/service/GroupMemberService.java
  src/main/java/org/be/group/service/GroupService.java
Labels: feature

#21 Feature/group
  src/main/java/org/be/auth/config/JwtAuthenticationFilter.java
  src/main/java/org/be/auth/config/JwtTokenProvider.java
  src/main/java/org/be/auth/config/SecurityConfig.java
  src/main/java/org/be/auth/service/CustomUserDetailsService.java
  src/main/java/org/be/community/service/CommunityPostService.java
Labels: chore

#22 feat : 소속한 group 내에서만 글 작성 가능하도록, 방장 게시물 삭제 권한 부여
  src/main/java/org/be/auth/config/SecurityConfig.java
  src/main/java/org/be/community/controller/CommunityPostController.java
  src/main/java/org/be/community/service/CommunityPostService.java
  src/main/java/org/be/group/service/GroupMemberService.java
Labels: feature

#23 Fix: 클라이언트 및 Flask와의 통신에서 요청, 응답 데이터 포멧 변경
  src/main/java/org/be/recommend/config/RedisConfig.java
  src/main/java/org/be/recommend/controller/RecommendController.java
  src/main/java/org/be/recommend/dto/BookDto.java
  src/main/java/org/be/recommend/dto/RecommendRequest.java
  src/main/java/org/be/recommend/dto/RecommendRequestMessage.java
  src/main/java/org/be/recommend/dto/RecommendResponse.java
  src/main/java/org/be/recommend/dto/RecommendResponseMessage.java
  src/main/java/org/be/recommend/dto/RecommendationMessage.java
  src/main/java/org/be/recommend/service/KafkaConsumerService.java
  src/main/java/org/be/recommend/service/KafkaProducerService.java
  src/main/java/org/be/recommend/service/RecommendService.java
Labels: fix
